title: Jue Wang (Daniel)
logo: /assets/img/IMG_6772.jpeg
description: Data Scientist 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
email: juewang2020@u.northwestern.edu
linkedin: https://www.linkedin.com/in/jue-wang-nwu/