title: Jue Wang (Daniel)
logo: /assets/img/IMG_6772.jpeg
description: 
Master of Science in Analytics student at Northwestern University
Data Scientist
Guitarist
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
